modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/DrexHD/quick-pack/issues"

[[mods]]
modId = "quick_pack"
version = "${modVersion}"
displayName = "quick-pack"
authors = "Drex"
description = "Improve datapack / resourcepack zip file loading times"
logoFile = "assets/quick-pack/icon.png"
logoBlur = false
displayURL = "https://github.com/DrexHD/quick-pack"

[[mixins]]
config = "quick-pack.mixins.json"